@baseurl=http://localhost:3000


### --- Afficher les articles
GET {{baseurl}}/
### --- add item
POST {{baseurl}}/items
Content-Type: application/json

{
    "title": "frederic.botella@gmail.com",
    "description": "moi",
    "url_image": "https://images.assetsdelivery.com/compings_v2/yupiramos/yupiramos2004/yupiramos200436847.jpg",
    "url_video": "",
    "user_id": "1",
    "category_id": "1"
}
### --- Afficher un article par son id
GET {{baseurl}}/items/1
### --- modifier un article par son id
PUT {{baseurl}}/items/3
Content-Type: application/json

{
    "title": "Tout sur les jeux vidéos 4",
    "description": "lol",
    "url_image": "https://images.assetsdelivery.com/compings_v2/yupiramos/yupiramos2004/yupiramos200436847.jpg",
    "url_video": "1",
    "user_id": "1",
    "category_id": "1"
}
### --- Supprimer un article par son id
DELETE  {{baseurl}}/items/3
### --- Afficher tous les users
GET {{baseurl}}/users
### --- Login user
POST {{{baseurl}}}/login
Content-Type: application/json

{
    "email": "frederic.botella@gmail.com",
    "password": "1234",
}
### --- add user
POST {{baseurl}}/users
Content-Type: application/json

{
    "email": "frederic.botella@gmail.com",
    "password": "1234",
    "username": "Fred"
}
### --- Afficher un user par son id
GET {{baseurl}}/users/2
### --- modifier un user par son id
PUT {{baseurl}}/users/1
Content-Type: application/json

{
    "email": "frederic.botella@gmail.com",
    "password": "1234",
    "username": "Fredo"
}
### --- Supprimer un user par son id
DELETE {{baseurl}}/users/1
### --- Afficher toutes les catégories
GET {{baseurl}}/categories
### --- Afficher unes catégories par son id
GET {{baseurl}}/categories/1
### --- Modifier une catégorie par son id
PUT {{baseurl}}/categories/1
### --- Effacer une carte par son id
DELETE  {{baseurl}}/categories/1
### --- Afficher tous les tags
GET  {{baseurl}}/tags
### --- Afficher un tag par son id
GET  {{baseurl}}/tags/1
### --- modifier un tag par son id
PUT   {{baseurl}}/tags/1
### --- Supprimer un tag par son id
DELETE  {{baseurl}}/tags/1

